source :rubygems

gem 'rails', '2.3.14'
gem 'rspec', '~> 1.3.2'
gem 'rspec-rails', '~> 1.3.2'
gem 'factory_girl', '1.2.2'
gem 'shoulda'
gem 'timecop'
gem 'curb'
gem 'super_exception_notifier'
gem 'handsoap'
gem 'sqlite3'
gem 'nokogiri'
gem 'mysql'
gem 'hpricot'
