# this file stores configuration values for each faculty
1:
  final_areas_on: create
  final_areas_count: 4
  attestation_month: 9
  attestation_day: 15
  consultant: true
2:
  final_areas_count: 4
  attestation_month: 11
  attestation_day: 30
  attestation_title: director
  dean_title: ředitel
4:
  final_areas_count: 4
  attestation_month: 9
  attestation_day: 11
5:
  final_areas_count: 4
  attestation_month: 12
  attestation_day: 1
6:
  final_areas_count: 4
  attestation_month: 1
  attestation_day: 31
14:
  final_areas_count: 5
  attestation_month: 10
  attestation_day: 18
15:
  final_areas_count: 5
  attestation_month: 1
  attestation_day: 30
