development:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: pepe
  password: p3p3
  socket: /usr/local/var/run/mysqld/mysqld.sock 

test:
  adapter: sqlite
  dbfile: db/test.db

production:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: pepe
  password: p3p3
