development:
  adapter: mysql
  database: phdstudy_devel
  host: localhost
  username: web
  password: w3b

test:
  adapter: mysql
  database: phdstudy-test
  host: localhost
  username: web
  password: w3b

production:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: web
  password: w3b
