development:
  adapter: sqlite
  dbfile: db/phdstudy.db

test:
  adapter: mysql
  database: rails_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: rails_production
  host: localhost
  username: root
  password: 
