development:
  adapter: mysql
  database: phdstudy_development
  host: localhost
  port: 3306
  encoding: utf8
  username: web
  password: w3b

test: &TEST
  adapter: mysql
  database: phdstudy_test
  host: localhost
  port: 3306
  encoding: utf8
  username: web
  password: w3b

production:
  adapter: mysql
  database: phdstudy_production
  host: edoktorand.czu.cz
  port: 3306
  encoding: utf8
  username: w3b
  password: w3b3000


cucumber:
  <<: *TEST