development:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: pepe
  password: p3p3

test:
  adapter: sqlite
  dbfile: db/test.db

production:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: pepe
  password: p3p3
