development:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: web
  password: w3b

test:
  adapter: mysql
  database: phdstudy-test
  host: localhost
  username: web
  password: w3b

production:
  adapter: mysql
  database: phdstudy
  host: localhost
  username: phdstudy
  password: s.S453sasD5
  socket: /var/lib/mysql/4.0/mysql.sock
