development:
  adapter: mysql
  database: phdstudy_production
  host: 10.70.1.75
  port: 3306
  username: web
  password: w3bw3b

test:
  adapter: mysql
  database: phdstudy_test
  host: 10.70.1.75
  port: 3306
  username: web
  password: w3bw3b

production:
  adapter: mysql
  database: phdstudy_production
  host: 10.70.1.75
  port: 3306
  username: web
  password: w3bw3b
