development:
  adapter: mysql
  database: phdstudy_development
  host: localhost
  port: 3306
  encoding: utf8
  username: web
  password: w3b

production:
  adapter: mysql
  database: phdstudy_production
  host: 10.70.1.75
  port: 3306
  encoding: utf8
  username: w3b
  password: w3b3000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST
