# this file stores configuration values for each faculty
1:
  final_areas_on: create   
  subjects_count: 5
  atestation_month: 9
  atestation_day: 15
  consultant: true
2:
  subjects_count: 4 
  atestation_month: 11
  atestation_day: 30
  atestation_title: director

3:
  subjects_count: 7 
  atestation_month: 9
  atestation_day: 20
4:
  subjects_count: 3  
  atestation_month: 1
  atestation_day: 31
5:
  subjects_count: 2  
  atestation_month: 1
  atestation_day: 31
6:
  atestation_month: 1
  atestation_day: 31
14:
  subjects_count: 4 
  atestation_month: 10
  atestation_day: 8
15:
  subjects_count: 4 
  atestation_month: 1
  atestation_day: 30
    
