# this file stores configuration values for each faculty
1:
  final_areas_on: create   
  subjects_count: 5
  atestation_month: 9
  atestation_day: 15
  consultant: true
2:
  subjects_count: 5 
  atestation_month: 11
  atestation_day: 30
3:
  subjects_count: 7 
  atestation_month: 9
  atestation_day: 20
4:
  subjects_count: 8  
  atestation_month: 1
  atestation_day: 31
5:
  subjects_count: 2  
  atestation_month: 1
  atestation_day: 31
6:
  atestation_month: 1
  atestation_day: 31
    
