#! /bin/sh

if [ $# -eq 1 ]
then
  filename=$1
else
  filename=`date "+phdstudy%Y-%m-%d.sql"`
fi

echo "# downloading db"
scp -P2222 edoktorand.czu.cz:dumps/$filename .

echo "# purgin db"
mysql -uweb -pw3b phdstudy_development < db/purge_db.sql

echo "# loading db"
cat db/set_utf8.sql $filename | mysql -uweb -pw3b phdstudy_development


echo "# cleaning"
rm $filename
