#! /bin/sh

if [ $# -eq 1 ]
then
  filename=$1
else
  filename=`date "+%Y-%m-%d.sql"`
fi

echo "# downloading db"
scp edoktorand.czu.cz:/dumps/$filename .

echo "# purgin db"
mysql -uweb -pw3b phdstudy_development < db/purge_db.sql

echo "# loading db"
cat db/set_utf8.sql $filename | mysql -uweb -pw3b phdstudy_development

echo "# migrating"
rake db:migrate

echo "# cleaning"
rm $filename
