#! /bin/sh

if [ $# -eq 1 ]
then
  filename=$1
else
  filename=`date "+%Y-%m-%d.sql"`
  archive=$filename.tgz
fi

if [ -f $filename ]
then
  purge=0
  echo "# local file"
else
  purge=1
  echo "# downloading db archive"
  scp edoktorand.czu.cz:/dumps/$archive .
  echo "# extracting dump"
  tar -xzvf $archive
fi


echo "# purgin db"
mysql -uweb -pw3b phdstudy_development < db/purge_db.sql

echo "# loading db"
cat db/set_utf8.sql $filename | mysql -uweb -pw3b phdstudy_development

echo "# migrating"
rake db:migrate

if [ "$purge" -ge 1 ]
then
  echo "# cleaning"
  rm $filename
  rm $archive
fi
