#!/usr/bin/env ruby

require "#{File.dirname(__FILE__)}/../config/environment"

require_dependency "search_system"

#-----------------------------------------------------------------------
# grab the first word on the command line as the term to search for
#-----------------------------------------------------------------------
search_terms = Array.new
if ARGV.size > 0 then
    search_terms << ARGV[0]
else
    puts "no search term given, searching for 'ruby'"
    search_terms << "ruby"
end

#-----------------------------------------------------------------------
# a mock contents so that we use the cache
#-----------------------------------------------------------------------
contents = MockContents.new
s = Search::Simple::Searcher.load(contents,"#{File.dirname(__FILE__)}/../db/search_cache")

#-----------------------------------------------------------------------
# do the search
#-----------------------------------------------------------------------
sr = s.find_words(search_terms)

if sr.contains_matches then
    puts "Score\t#File"
    sr.results.sort.each do |res|
        puts "#{res.score}\t#{res.name}"
    end
else
    puts sr.warnings
    puts "No matches"
end
    
